name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create deployment directory
      run: |
        mkdir -p deploy
        # Copy only necessary files for static hosting
        cp index.html deploy/
        cp styles.css deploy/
        cp script.js deploy/
        cp kanji-data.js deploy/
        cp audio-manager.js deploy/
        cp storage-manager.js deploy/
        cp manifest.json deploy/
        cp sw.js deploy/
        cp README.md deploy/
        # Copy docs if they exist
        if [ -d "docs" ]; then cp -r docs deploy/; fi
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './deploy'
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4